### ISSUE TITLE
[Bug] `seeds/apple_store_country_codes.csv`(ISO-3166 country codes) needs a refresh.

### ISSUE THREAD

**Issue by moxordo** [fivetran/dbt_apple_store_source#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Would it be possible to refresh the apple_store_country_codes to reflect the most recent version of ISO-3166 country codes?

The staleness seems to affect downstream data models such as `[apple_store__territory_report](https://github.com/fivetran/dbt_apple_store/blob/9735693405f64101beae5ef8129681363ca8b8b4/models/apple_store__territory_report.sql)`, with `territory_short` columns being NULL for certain countries such as the following:
![image](https://user-images.githubusercontent.com/29856365/231324341-929e7ee1-4b1d-4148-a94c-3321900c1c73.png)

I would be happy to update the country codes, if you can provide me with the source for the data 😁.

### Expected behavior

Preferrably, the `territory_short` column of the model `[apple_store__territory_report](https://github.com/fivetran/dbt_apple_store/blob/9735693405f64101beae5ef8129681363ca8b8b4/models/apple_store__territory_report.sql)` should reflect the latest ISO-3166 country codes.

### dbt Project configurations

```
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "droom_analytics_bq"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "droom_analytics_bq"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  apple_store:
    +schema: itunes_connect # leave blank for just the target_schema
  apple_store_source:
    +schema: itunes_connect # leave blank for just the target_schema
  google_play:
    +schema: google_play # leave blank for just the target_schema
  google_play_source:
    +schema: google_play # leave blank for just the target_schema

    # Config indicated by + and applies to all files under models/example/
    #

vars:
  # enable subscriptions and earnings models (https://github.com/fivetran/dbt_app_reporting#step-4-disable-and-enable-source-tables)
  apple_store__using_subscriptions: true # by default this is assumed to be false
  google_play__using_subscriptions: true # by default this is assumed to be false
  google_play__using_earnings: true # by default this is assumed to be false

```

### Package versions

```
packages:
  - package: fivetran/apple_store
    version: 0.2.0
  - package: fivetran/google_play
    version: 0.2.0

```

### What database are you using dbt with?

bigquery

### dbt Version

```
Core:
  - installed: 1.4.4
  - latest:    1.4.5 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.4.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
  ```

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
